apiVersion: v1
kind: ConfigMap
metadata:
  name: gemini-config
  namespace: gemini-namespace
data:
  GOOGLE_ID: 473932088770-pkp783blog7ccvq3ru0fpi3uogdvc1n9.apps.googleusercontent.com
  MONGODB_URI: mongodb://mongodb-service:27017/gemini
  NEXTAUTH_URL: https://13.201.34.247.nip.io
  MONGO_INITDB_ROOT_USERNAME: admin
